version: '3.8'

services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootuser
      MYSQL_DATABASE: profileDB
    ports:
      - "3308:3306"  # Cổng của MySQL
    volumes:
      - mysql-data:/var/lib/mysql  # Dữ liệu MySQL sẽ được lưu trong volume
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Node.js Application Service
  app:
    build: .
    container_name: node-api
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootuser
      DB_NAME: profileDB
    ports:
      - "3000:3000"  # Cổng của ứng dụng
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
