version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootuser
      - DB_NAME=profileDB
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootuser
      MYSQL_DATABASE: profileDB
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
